Remove duplicates that differ only in their capitalization
This was more or less straightforward. There were only two exceptions: "html" and "SMIL10". The first one pointed to "html5" even though "HTML" represents the WHATWG HTML spec. I decided to simply remove "html" which means that from now onwards it will point to the living standard instead of HTML5. The other tricky case was about smil. "smil" represents SMIL 1.0 while its "SMIL" represents SMIL 2.0. "SMIL10" pointed to "smil" but since I removed that one, I simply copied its contents to "SMIL10".

I tried to map "SMIL10" to "SMIL-19980615" but that resulted in the following error:

    Reference [[SMIL10]] has no other properties.:
    AssertionError: aliases is a prop

@tobie, any idea why this happens? biblio.json definitely doesn't contain that property.

This addresses tobie/specref#22